---
- hosts: hana
  remote_user: cloudadmin
  become: true
  become_user: root
  vars:
    # is_primary is selected so that tasks that need to be issued one are honoured correctly
    is_primary: "{{ ansible_play_hosts[0] == inventory_hostname }}"
    primary_hostname: "{{ ansible_play_hosts[0] }}"

  pre_tasks:
    - name: Detect cloud platform
      ansible.builtin.include_tasks:
        ./tasks/detect-cloud-platform.yaml
    - name: Detection result
      ansible.builtin.debug:
        msg: "Cloud platform appears to be {{ cloud_platform_name }}"

    - name: Load SAP HANA variables
      ansible.builtin.include_vars: ./vars/hana_vars.yaml

  tasks:
    - name: Refresh MS
      ansible.builtin.command: "crm resource refresh msl_SAPHana_HDB_{{ sap_hana_install_sid }}{{ sap_hana_install_instance_number }}"
      when: is_primary

    - name: Wait for cluster to settle
      ansible.builtin.command: "cs_wait_for_idle -s 5"
      when: is_primary

    - name: MS Resource Maintenance off
      ansible.builtin.command: "crm resource maintenance msl_SAPHana_HDB_{{ sap_hana_install_sid }}{{ sap_hana_install_instance_number }} off"
      when: is_primary
